<header class="header">
    <div class="row">
        <div class="nav">
            <button class="nav-button"></button>
            <nav id="menu">
                <ul>
                    <li><a href="<?=SITE_HOME_ADMIN?>">Home</a></li>
                    <li><a href="<?=SITE_HOME_ADMIN?>import_guests.php">Import Guest List</a></li>
                    <li><a href="<?=SITE_HOME_ADMIN?>list_guests.php">Manage Guest List</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>