<header class="header">
    <div class="row">
        <div class="nav">
            <button class="nav-button"></button>
            <nav id="menu">
                <ul>
                    <li><a href="<?=SITE_HOME?>">Home</a></li>
                    <li><a href="<?=SITE_HOME?>big-day.php">The Big Day</a></li>
                    <li><a href="<?=SITE_HOME?>venue.php">Venue</a></li>
                    <li><a href="<?=SITE_HOME?>where-to-stay.php">Where to stay</a></li>
                    <li><a href="<?=SITE_HOME?>gifts.php">Gifts</a></li>
                    <li><a href="<?=SITE_HOME?>photos.php">Photos</a></li>
                    <li><a href="<?=SITE_HOME?>contact.php">Contact</a></li>
                    <li><a href="<?=SITE_HOME?>rsvp.php">RSVP</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>