<!-- CSS and Fonts
   ================================================== -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="<?= SITE_HOME;?>css/style.css" type="text/css" media="screen" />

<!-- JS Scripts
================================================== -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="<?= SITE_HOME;?>js/jquery.slicknav.min.js"></script>