<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="en-gb" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?=$page_desc?>">
    <title><?=$page_title?> | Sean &amp; Karla are getting married | Barnes Wedding 2018</title>

    <?php require_once '/inc/js-styles.inc';?>
</head>
<body>
<div id="wrapper">
    <?php require_once '/inc/header.inc';?>